### ISSUE TITLE
Regular expression for TTS Text Replacement

### ISSUE THREAD

**Issue by pilot51** [pilot51/voicenotify#102]
### Discussed in https://github.com/pilot51/voicenotify/discussions/101

<div type='discussions-op-text'>

<sup>Originally posted by **ngkwtys** May 28, 2023</sup>
Hi, can I use regular expressions in TTS Text Replacement?
If this is possible, it would allow me to quickly find out the expected seismic intensity of an earthquake.
Unfortunately, most earthquake warning apps only scare people with noisy alerts, but Voice Notify has the potential to calmly respond to earthquakes.</div>

**Comment by ngkwtys** [comment]
Maybe I shouldn't comment here, but I just wanted to say thank you.

Voice Notify successfully alerted me on the 2024 Sea of Japan earthquake. 
Earthquake app: "Beep! Beep!"  (useless)
VN: "Earthquake Early Warning Earthquake intensity 3 approximately XX seconds after occurrence Date: 2023/01/01 16:10 Epicenter: Noto, Ishikawa Prefecture Maximum intensity 7"

I have finished the Japanese translation, hope it helps.

**Comment by pilot51** [comment]
That's great to hear! Glad you're safe! Stories like that bring meaning to the project.

Thanks for the translation. Google's latest statistics from 2 days ago show 170 active users of the Japanese language. They will all benefit from your work and your translation for the store should help the app grow in the Japanese community.
