### ISSUE TITLE
Voice notifications not disabled during Signal calls

### ISSUE THREAD

**Issue by uhkeller** [pilot51/voicenotify#111]
I just was in a long Signal call using a headset with the display off, which are the conditions I have set up for Voice Notify to be active (headset and display off, I mean). During the call there were several spoken notifications which was quite distracting. I read in some other issues here that voice notification are disabled during regular calls, but apparently not for calls in third-party apps. It would be nice if this could be implemented.

**Comment by gaabora** [comment]
Same in "teams" app

**Comment by pilot51** [comment]
I haven't tested any third party apps yet, but it should be fixed in fc3913f.
