### ISSUE TITLE
Feature request: Per-app TTS message settings

### ISSUE THREAD

**Issue by megamuzzy** [pilot51/voicenotify#113]
I've been using Enhanced SMS and Caller Id (eCID) app to read notifications for over 10 years. Several years ago, this application was removed from the play market, but continued to work properly. Unfortunately, recently (in October) eCID became unusable.

I am very glad that I found your Voicenotify application. The only thing I miss in your app is the ability to customize the TTS message settings individually for each application (as was implemented in eCID)

If possible, please implement this feature your app.

Thanks!

**Comment by TippyLion28** [comment]
Absolutely +1

Sometimes it's useful to read only the notification body such as in messaging apps. But for my reminders it would be more useful to read only the notification title :)

**Comment by Telhop** [comment]
I would find this useful as well. I find that different apps construct the notification messages differently. Currently I get around this the best I can by very careful use of text replacement.
