### ISSUE TITLE
A question about the ‘Ignore Empty’ option

### ISSUE THREAD

**Issue by Telhop** [pilot51/voicenotify#123]
Does it operate on the final TTS message text to be sent out or the (raw) notification itself?  
If it is the former, the problem this gives me is that I configure the messages to include the app name (which I would guess is quite common). This means the final text of the TTS message is never going to be empty, even if the actual notification is empty, as the final text will include the app name. 
If the ‘Ignore Empty’ option  works on the (raw) notification, I have evidence that it is not working. 
Version: 1.3.1 [7ccf0f7]

**Comment by pilot51** [comment]
It operates on the final TTS message, and you're right, that will almost never work.

It looks like 520ac19 (back in 2017) is where I broke it by switching the empty check to the TTS message without realizing the consequences and neglecting to test it. That gives me another idea for a customizable test notification.

The solution I have in mind is to check that all of the notification parts used by the TTS message are empty, excluding the app name and parts not used.
