### ISSUE TITLE
Feature request: change app language

### ISSUE THREAD

**Issue by Mikaela** [pilot51/voicenotify#125]
Sometimes when looking for specific settings or developing translations it would be helpful to have the app in different language than the system.

I think this is somehow natively supported by Android as in Settings -> apps -> YouTube Music there is an option for language which also appears with some other apps, although not in Voice Notify that this issue is about.

**Comment by pilot51** [comment]
I've thought about doing this, but I was not aware of the native support, which should make it much easier to implement than I expected. Thanks for pointing it out!
