### ISSUE TITLE
Word replacement

### ISSUE THREAD

**Issue by pilot51** [pilot51/voicenotify#33]
Replace words in a notification with another word. They should be saved to a list. Useful for censoring, correcting pronunciation, etc.

**Comment by EvanDotPro** [comment]
I'd love to see this make it in for the next version. Wish I had the time to make an attempt at a PR myself. :disappointed:

**Comment by akbarzg** [comment]
Replacing a word pattern with another word will be more powerful feature. If any word begins with "http:" then I should be able to replace it with some another word (say "Link")

Please implement this enhancement in the next release.

**Comment by pilot51** [comment]
Added in 205ca7b. At this point, it's simple (no regex support for example) and has a focus issue, but it's a start and it works.
