### ISSUE TITLE
notify while ringing call

### ISSUE THREAD

**Issue by artek70** [pilot51/voicenotify#38]
I suggest (option) to enable notification while call is ringing to hear caller name (who is ringing). I see in log Telephone notification is blocked while "active or ringing call".

**Comment by pilot51** [comment]
Added in commit referenced above. It will speak while ringing and stop as soon as the call is answered. Right now it is a very simple solution that uses the same message format as other notifications and will not prioritize the call over other notifications ahead of it in the speech queue. I may improve on it later, but feel free to comment or open a new issue if you find you would like it improved.
