### ISSUE TITLE
Doesn't work after Lollipop upgrade

### ISSUE THREAD

**Issue by jueves** [pilot51/voicenotify#49]
It worked fine in my Moto G 2013  until I upgraded to Lollipop. Test notifications are showed but not spoken. I've checked accesibility settings and tested voice synthesis in Android settings, but couldn't fix it.
Could it be an incompatibility with Lollipop or is just me?

**Comment by jueves** [comment]
It worked after I disable and enable again voice notifications in Android settings. I have rebooted my phone several times since I upgrade to Lollipop, so maybe Voice Notify is starting too soon after boot.
My phone is encrypted, but also was before upgrade and everything worked fine.

**Comment by ppalaga** [comment]
@jueves thanks, the workaround worked for me!

**Comment by pilot51** [comment]
Related to #31 and #55.

I was never able to reproduce. However, this was very likely fixed in 682bbb7 by reading notifications through Notification Listener Service instead of Accessibility Service.
