### ISSUE TITLE
Doesn't announce caller ID on MIUI 8

### ISSUE THREAD

**Issue by F5System** [pilot51/voicenotify#56]
I want to hear caller's name during incoming call rings while I'm in headphones without taking my phone from pocket, but it doesn't work.

Caller's name and phone appears in notification shade, VoiceNotify has access to "Accessibility" option, other notifications works perfectly. I also tried different TTS Audio Streams while call with no success. And there is no call event in VN Notification Log.

I tried free app "Shouter" [https://play.google.com/store/apps/details?id=com.bhkapps.shouter](url), it works and announce callers name. It requires not "accessibility" access, but by asking permissions to "phone", "contacts", "get device id" and other permissions.

But I want to use your app, it completely satisfies me, and I like open source software )
What can I try to get voice announce of caller ID?

Phone: Xiaomi Redmi 4
Android: 6.0.1
MIUI 8 latest 7.1.20
VoiceNotify: 1.0.12

**Comment by F5System** [comment]
For myself I solved this with Tasker [https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm](url), but hope there will be solution for VoiceNotify for those, who doesn't use Tasker.



Here is the simple solution for Tasker:

First **profile** you will make should be called "Incoming Call"
Create an **Event context**, go to Phone --> Phone Ringing. Leave the caller field blank. Exit out, and create a new **task**. You can name it if you want, but it's not necessary.
Once inside the **task**, your first action will be to create a **Say command**. Go to Alert --> Say. For the text you want the TTS to say, type in something like
`Incoming call from %CNAME`
I would recommend you uncheck "Respect Audio Focus" so Tasker notifying you of a call will take precedence over whatever other audio is playing from your phone.

Taken from here [https://forum.xda-developers.com/u/tasker-tips-tricks/guide-driving-mode-answer-calls-texts-t3332004](url)

**Comment by pilot51** [comment]
This will go under #38. I'll see about duplicating your Tasker solution so it only announces the caller and no other notifications during the call.

**Comment by pilot51** [comment]
Added in commit referenced above. It will speak while ringing and stop as soon as the call is answered. Right now it is a very simple solution that uses the same message format as other notifications and will not prioritize the call over other notifications ahead of it in the speech queue. I may improve on it later, but feel free to comment or open a new issue if you find you would like it improved.
