### ISSUE TITLE
Feature Request: translation dictionary

### ISSUE THREAD

**Issue by haxwithaxe** [pilot51/voicenotify#57]
it would be great to have a way to provide translations for words that tts pronounces incorrectly.
example:
GroupMe (chat app) is pronounced groopmah
the translation would be: group me

**Comment by pilot51** [comment]
Duplicate of #33.

I plan to resume development of VN soon (finally), once I finish up some work on another project.

**Comment by pilot51** [comment]
Added in 205ca7b. At this point, it's simple (no regex support for example) and has a focus issue, but it's a start and it works.
