### ISSUE TITLE
Rereading entire updated notifications

### ISSUE THREAD

**Issue by haxwithaxe** [pilot51/voicenotify#61]
v1.1.2 is rereading the whole notification when that notification is updated.
I've only noticed this with telegram but that is the only app that gets stacked up like that for me.
Let me know if there is anything I can do to help.

# Expected
1. Existing notification `hello, world`
2. Reads: "hello, world"

3. Notification is updated to append "how are you".
  Displays:
  ```
  hello, world
  how are you
  ```
4. Reads: "how are you"

# Observed
4. Reads "hello, world how are you"

**Comment by pilot51** [comment]
Is the updated notification the same one or a new one in Telegram's notification group (appearing as a single notification when the group is collapsed)? If the former, a fix to determine what has already been spoken in an updated notification may be a bit more complicated. I am aware of the latter happening in some cases, such as with Gmail, where it repeats notifications from a group when a new notification is added to the group, which I still need to get around to fixing.

**Comment by haxwithaxe** [comment]
I think it's as a group.
