### ISSUE TITLE
[Suggestion] New App Icon 

### ISSUE THREAD

**Issue by cedenoruel** [pilot51/voicenotify#65]
Hi! I find this app really useful so I decided to contribute. As you may have noticed, simple and minimalist icons are trending right now. Thus, here are my suggestions for the  app icon in order to give it a modern look and a brand identity. These icons combine symbol for "notification" (bell) and " human e-voice" which well-represent what this app is capable of.  What do you think? I'll be happy to make adjustments. 

![request_2](https://user-images.githubusercontent.com/38007519/39370380-efd4484c-4a68-11e8-9c20-ed54f0cea665.png)

![request_3](https://user-images.githubusercontent.com/38007519/39396836-edc02384-4b1f-11e8-9ced-b116e2dbb4a1.png)

![design_attempts](https://user-images.githubusercontent.com/38007519/39806458-3402b2d0-53a4-11e8-9e2d-eefe98441a95.png)

**Comment by cedenoruel** [comment]
Glad you like it.  Will it be okay to send the vectors and files via pull request? If you have further suggestions, please let me know.

**Comment by cedenoruel** [comment]
Glad you like it. I made some blue/cyan variations as you mentioned. Which one do you prefer? I will upload the vectors and png files of your final pick. 

![request_4](https://user-images.githubusercontent.com/38007519/39397144-9aa66d20-4b24-11e8-9524-2af2ddba94a7.png)

**Comment by cedenoruel** [comment]
![color](https://user-images.githubusercontent.com/38007519/39508629-6c144f4a-4e0d-11e8-9581-d96e8dfc0b96.png)


Great! I  uploaded the vectors and exports in a google drive which you can access [here](https://drive.google.com/drive/folders/1HHURlO_UK2vx3mAtDObt4H4-Ws0nAw1F?usp=sharing) with included license. Thank you for the opportunity to contribute to this project. 

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by HorstiG** [comment]
The third blue is best for me. But I love also your old.
