### ISSUE TITLE
tts text replacement

### ISSUE THREAD

**Issue by jeffrypabuaran** [pilot51/voicenotify#71]
i want to ask, how to build tts text replacement? and are you use a database for the text replacement?

**Comment by pilot51** [comment]
You're asking how to implement it for your own project?

It extends DialogPreference and as such is saved to shared preferences. You can see the code in [TextReplacePreference.java](https://github.com/pilot51/voicenotify/blob/master/app/src/main/java/com/pilot51/voicenotify/TextReplacePreference.java).

**Comment by jeffrypabuaran** [comment]
thank you..
one more question, if i use sqlite to save text replacement, what code i
have to implement?

**Comment by pilot51** [comment]
That would not be a simple answer, certainly nothing I can provide in the 10 minutes I have until I leave for work. I would suggest you understand the class I provided and how SQLite works. ORMLite might make things a little easier. Once you reasonably understand them, it shouldn't be too difficult to implement, just a bit time-consuming.
