### ISSUE TITLE
Correct method to ignore specific google voice notification

### ISSUE THREAD

**Issue by famewolf** [pilot51/voicenotify#78]
I have a notification from google voice (which also handles my sms messages) that says "Voice<pause>Voice is doing work in the background".   I have set "Voice is doing work in the background both as a text replacement to "" and also set the app to ignore any notification that has "Voice is doing work in the background" and one of them appears to be working for the most part...the problem is the app still reads out the word "Voice" from the part where it is announcing the APP which wrote the notification.   How can I correctly ignore this notification without ignoring google voice as a whole?  Thank you for your time and for making this great app.

**Comment by pilot51** [comment]
This appears to be caused by the same thing as #79. Ignored text applies after the TTS Message formatting and you probably need a `.` after a part of the notification if you're using the default format. I'll clarify that in the dialog message.
